# Uncomment the next line to define a global platform for your project
 use_frameworks!
 platform :ios, '9.0'

target 'Ejianqian' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for Ejianqian

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'

end
